package:
  name: swig
  version: 2.0.8

source:
  fn: swig-2.0.8.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-2.0.8.tar.gz

requirements:
  build:
    - pcre
    - python
  run:
    - pcre
    - python

about:
    home: http://www.swig.org/
    license: GPLv3
