package:
  name: enversion
  version: 0.2.7

source:
  fn: enversion-v0.2.7.tar.gz [not win]
  url: https://github.com/tpn/enversion/archive/v0.2.7.tar.gz [not win]

build:
  number: 0
  entry_points:
    - evnadmin = evn.admin.cli:main

requirements:
  build:
    - python
    - subversion

  run:
    - python
    - subversion

test:
  commands:
    - evnadmin version
  imports:
    - evn

about:
  home: http://github.com/tpn/enversion
  license: Apache v2
  summary: 'Enterprise Subversion'

# vim:set ts=8 sw=2 sts=2 tw=78 et:
