package:
  name: serf
  version: 1.2.1

source:
  #fn: tpn-apr-1.5.0-win32.zip [win]
  #url: https://github.com/tpn/apr-win/archive/1.5.0-vc9.zip [win]
  fn: serf-1.2.1.tar.bz2 [not win]
  url: http://serf.googlecode.com/files/serf-1.2.1.tar.bz2 [not win]

build:
  number: 0

requirements:
  build:
    - apr
    - apr-util
    - openssl
  run:
    - apr
    - apr-util
    - openssl

about:
  home: https://code.google.com/p/serf/
  license: Apache License 2.0

# vim:set ts=8 sw=2 sts=2 tw=78 et:
