package:
  name: httpd
  version: 2.2.26

source:
  #fn: tpn-apr-1.5.0-win32.zip [win]
  #url: https://github.com/tpn/apr-win/archive/1.5.0-vc9.zip [win]
  fn: httpd-2.2.26.tar.bz2 [not win]
  url: http://apache.osuosl.org//httpd/httpd-2.2.26.tar.bz2 [not win]

build:
  number: 0

requirements:
  build:
    - apr
    - apr-util
    - apr-iconv
    - pcre
    - zlib
    - openssl
    - expat
  run:
    - apr
    - apr-util
    - apr-iconv
    - pcre
    - zlib
    - openssl
    - expat

about:
  home: http://httpd.apache.org/
  license: Apache License 2.0

# vim:set ts=8 sw=2 sts=2 tw=78 et:
